//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debi.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reghot", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string reghot(int hid, string htlname, string loc, string dsc, string pnum, string pswrd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reghot", ReplyAction="*")]
        System.Threading.Tasks.Task<string> reghotAsync(int hid, string htlname, string loc, string dsc, string pnum, string pswrd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet login(int hid, string pswrd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> loginAsync(int hid, string pswrd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addroom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string addroom(int hid, string type, string prc, string avl, string imgid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addroom", ReplyAction="*")]
        System.Threading.Tasks.Task<string> addroomAsync(int hid, string type, string prc, string avl, string imgid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registerRooms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string registerRooms(int hid, string type, string prc, string avl, string imgid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registerRooms", ReplyAction="*")]
        System.Threading.Tasks.Task<string> registerRoomsAsync(int hid, string type, string prc, string avl, string imgid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Viewss", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Viewss();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Viewss", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ViewssAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Updateroom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Updateroom(int hid, string type, string prc, string avl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Updateroom", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateroomAsync(int hid, string type, string prc, string avl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteR(int hid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteR", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DeleteRAsync(int hid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Searcc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Searcc(string hname, string loc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Searcc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearccAsync(string hname, string loc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Searcc2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Searcc2(string hname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Searcc2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Searcc2Async(string hname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Searcc3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Searcc3(int rid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Searcc3", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Searcc3Async(int rid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Debi.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Debi.ServiceReference1.WebService1Soap>, Debi.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string reghot(int hid, string htlname, string loc, string dsc, string pnum, string pswrd) {
            return base.Channel.reghot(hid, htlname, loc, dsc, pnum, pswrd);
        }
        
        public System.Threading.Tasks.Task<string> reghotAsync(int hid, string htlname, string loc, string dsc, string pnum, string pswrd) {
            return base.Channel.reghotAsync(hid, htlname, loc, dsc, pnum, pswrd);
        }
        
        public System.Data.DataSet login(int hid, string pswrd) {
            return base.Channel.login(hid, pswrd);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> loginAsync(int hid, string pswrd) {
            return base.Channel.loginAsync(hid, pswrd);
        }
        
        public string addroom(int hid, string type, string prc, string avl, string imgid) {
            return base.Channel.addroom(hid, type, prc, avl, imgid);
        }
        
        public System.Threading.Tasks.Task<string> addroomAsync(int hid, string type, string prc, string avl, string imgid) {
            return base.Channel.addroomAsync(hid, type, prc, avl, imgid);
        }
        
        public string registerRooms(int hid, string type, string prc, string avl, string imgid) {
            return base.Channel.registerRooms(hid, type, prc, avl, imgid);
        }
        
        public System.Threading.Tasks.Task<string> registerRoomsAsync(int hid, string type, string prc, string avl, string imgid) {
            return base.Channel.registerRoomsAsync(hid, type, prc, avl, imgid);
        }
        
        public System.Data.DataSet Viewss() {
            return base.Channel.Viewss();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ViewssAsync() {
            return base.Channel.ViewssAsync();
        }
        
        public string Updateroom(int hid, string type, string prc, string avl) {
            return base.Channel.Updateroom(hid, type, prc, avl);
        }
        
        public System.Threading.Tasks.Task<string> UpdateroomAsync(int hid, string type, string prc, string avl) {
            return base.Channel.UpdateroomAsync(hid, type, prc, avl);
        }
        
        public string DeleteR(int hid) {
            return base.Channel.DeleteR(hid);
        }
        
        public System.Threading.Tasks.Task<string> DeleteRAsync(int hid) {
            return base.Channel.DeleteRAsync(hid);
        }
        
        public System.Data.DataSet Searcc(string hname, string loc) {
            return base.Channel.Searcc(hname, loc);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearccAsync(string hname, string loc) {
            return base.Channel.SearccAsync(hname, loc);
        }
        
        public System.Data.DataSet Searcc2(string hname) {
            return base.Channel.Searcc2(hname);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Searcc2Async(string hname) {
            return base.Channel.Searcc2Async(hname);
        }
        
        public System.Data.DataSet Searcc3(int rid) {
            return base.Channel.Searcc3(rid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Searcc3Async(int rid) {
            return base.Channel.Searcc3Async(rid);
        }
    }
}
